export const SET_SESSION = 'SET_SESSION';
export const SET_USER = 'SET_USER';
export const RESET_SESSION = 'RESET_SESSION';
export const MERGE_GENRE_ACTIVITIES = 'MERGE_GENRE_ACTIVITIES';
export const SET_SELECTED_GENRE = 'SET_SELECTED_GENRE';
export const SET_PAGINATE_LINK = 'SET_PAGINATE_LINK';
export const SET_REQUEST_IN_PROCESS = 'SET_REQUEST_IN_PROCESS';
export const GET_GENRE_DATA_FROM_CLOUD = 'GET_GENRE_DATA_FROM_CLOUD';
